### ISSUE TITLE
Running a single epoxy 

### ISSUE THREAD

**Issue by hannahcook17** [mikaelsimard5/ProtonPhotonEquivalence#1]
Hi Mikeal, 
I am struggling to work out the best way to fix an issue with the code. 
When I want to define a certain epoxy (for example CB4) in line 140 ( epoxy_indexes_to_mix = 4;); it will run with CB1 because the line 147 is defined as nepoxies_permutation = length(epoxy_indexes_to_mix); so this makes the value 1. This value is then inputted into the loop on line 151. so i=1:1. 

Any ideas?

**Comment by mikaelsimard5** [comment]
Hi Hannah,

1) are you sure you are using the correct version ? In the code on github I see the line "nepoxies_permutation = length(epoxy_indexes_to_mix)” at line 160, not 140. The other line you refer to (the loop - for ce = 1:nepoxies_permutation ) starts at line 164. Let’s solve this first.

2) It will work anyway because of the first line when you get into the loop: 
    current_epoxy_number = epoxy_indexes_to_mix(ce);
It will use the ce^{th} index of epoxy_indexes_to_mix as your mixture index. epoxy_indexes_to_mix(ce), when ce=1, will be thus equal to 4.

**Comment by hannahcook17** [comment]
Yes, it is the same. i have just removed a couple of lines out - running for the bone library as it is part of the soft tissue library. so it moved the lines up. 

when I run for epoxy 4: it calculates the following formulations 
Now testing epoxy #4 out of #4.
Elapsed time is 0.003141 seconds.
----------------------------------------------------------------
RELATIVE MASS FRACTION OF THE OPTIMAL MIXTURE
CB1(AralditeMY750+Synolide) mass fractional weight: 33.14%.
Calciumcarbonate mass fractional weight: 66.86%.
Polyethlyene mass fractional weight: 0.00%.
Phenolicmicrospheres mass fractional weight: 0.00%.
----------------------------------------------------------------
MASS DENSITY (g/cm^3).
Mixture vs target material: 1.866 vs 1.850.
Relative difference: -0.888 %.
----------------------------------------------------------------
MASS ATTENUATION COEFFICIENT (cm^2/g).
Mixture vs target material: 0.412 vs 0.403.
Relative difference: -2.253 %.
----------------------------------------------------------------
RELATIVE STOPPING POWER.
Mixture vs target material: 1.643 vs 1.659.
Relative difference: 0.971 %.
----------------------------------------------------------------
SCATTERING LENGTH.
Mixture vs target material: 18.360 vs 18.194.
Relative difference: -0.912 %.
----------------------------------------------------------------
NUCLEAR CROSS SECTIONS.
1) Reaction cross section at 50/200 MeV.
Mixture vs target material: 0.024/0.017 vs 0.023/0.017.
Relative difference: -3.444/-0.568 %.
2) proton production cross section at 50/200 MeV.
Mixture vs target material: 0.369/0.701 vs 0.346/0.677.
Relative difference: -6.390/-3.655 %.
3) alpha production cross section at 50/200 MeV.
Mixture vs target material: 0.137/0.178 vs 0.138/0.178.
Relative difference: 0.730/-0.375 %.
----------------------------------------------------------------
HU.
Mixture vs target material: 2473.522 vs 2367.102.
----------------------------------------------------------------
Electron density.
Mixture vs target material: 1.723 vs 1.737.
Relative difference: 0.823 %.
----------------------------------------------------------------
It is using CB1 

Any ideas?

**Comment by hannahcook17** [comment]
Sorry for the horrid copy and paste. it looks awful

**Comment by mikaelsimard5** [comment]
My bad, it was just a small mistake in the display at the end. The code processed CB4 but printed the name if epoxy index 1 instead of 4. Just pushed a new version where it's corrected.
